version: '3.7'
services:
  order_app:
    container_name: order-grpc
    build: .
    restart: on-failure
    volumes:
      - ./:/app/
    networks:
      - echo-stack
    ports:
      - 3000:3000
      - 50051:50051
      - 50052:50052
      - 50053:50053
    depends_on:
      - postgres-service
  postgres-service:
    image: postgres
    restart: always
    container_name: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_svc
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

networks:
  echo-stack:
    driver: bridge